# Generated by Django 5.1.3 on 2024-12-02 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finance_type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], max_length=128)),
                ('finance_category', models.CharField(choices=[('ATUALIZACAO_JOIA', 'Atualização de Jóias'), ('CONSULTA', 'Consultas'), ('EQUIPAMENTO', 'Compra de Equipamentos'), ('FIXAS', 'Despesas Fixas'), ('LICENCAS', 'Licenças'), ('LUCROS', 'Divisão de Lucros'), ('MANUTENCAO', 'Manutenções Gerais'), ('MARKETING', 'Marketing'), ('MATERIAL_ESCRITORIO', 'Material de Escritório'), ('MATERIAL_PRODUCAO', 'Material de Produção'), ('PERFURACAO', 'Perfurações'), ('RESERVA', 'Reserva'), ('TAXAS_IMPOSTOS', 'Taxas e Impostos'), ('TREINAMENTO', 'Treinamenos & Especializações'), ('VENDA_JOIA', 'Vendas de Jóias')], max_length=128)),
                ('payment_type', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PERMUTA', 'Permutas'), ('PIX', 'Pix')], max_length=128)),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateField()),
                ('appointment_hour', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('PERFURACAO', 'Perfuração'), ('ATUALIZACAO', 'Atualização'), ('ATENDIMENTO', 'Atendimento'), ('CONSULTA', 'Consulta')], max_length=128)),
                ('appointment_status', models.CharField(choices=[('ABERTO', 'Aberto'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('PENDENTE', 'Pendente')], max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='queenbee_api.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
